### PR TITLE
Added "inputStyle" property

### PR DESCRIPTION
**Pull request by GabiAxel**

### CODE REVIEW

**Comment by felixakiragreen** [comment]
What style do you want to pass to the input?

It should be possible to style any elements using CSS directly, that's what I do.

**Comment by GabiAxel** [comment]
I saw it's possible to use CSS, but I would like to use JS inline styles.

**Comment by krainboltgreene** [comment]
Honestly I feel like Kronos should pass through most major input field keys:
- styles
- on*
- name
- required
- className

**Comment by dalkir** [comment]
I totally agree with @krainboltgreene. I'm trying to serialize a form by the field names but the input with the kronos' value doesn't have a name and I realized that it doesn't have the `name` prop.
May I submit a PR adding at least the `name` prop ?

**Comment by felixakiragreen** [comment]
Absolutely @dalkir

**Pull request closed without merging**
