### PR TITLE
Update packages, use prop-types instead of React.propTypes

### PR DESCRIPTION
**Pull request by michaelryancaputo**
Hey there,

Who likes warnings? Not me!

This PR should get rid of those warnings 👯‍♂️

### CODE REVIEW

**Comment by michaelryancaputo** [comment]
Closing this because no ❤️

**Comment by felixakiragreen** [comment]
My bad. I've been swamped at work recently. I will try to look at these this weekend and push a new release.

**Comment by felixakiragreen** [comment]
I merged your code and now I'm getting this error:

screen shot 2017-06-13 at 11 37 59

Still throws the error even when I refactor all PropTypes. I'm currently investigating.

**Comment by michaelryancaputo** [comment]
I don't have time to check this morning, but are you using the new build of React `15.6.0`?

**Comment by michaelryancaputo** [comment]
I'm wondering if this is related to using `static propTypes`, possibly a new warning, or error.

**Comment by felixakiragreen** [comment]
It gave the error for both `static propTypes` and `Component.propTypes = { ... }`. Looks like it might be related to HoC's.

**Pull request merged**
